language: python
python:
  - "3.6"
install:
  - pip install pytest pycodestyle pyflakes vulture
script:
  - pyflakes .
  - pycodestyle --max-line-length=120 .
  - vulture --min-confidence=100 .
  - pytest
