columns_for_drop = [
    'Unnamed: 0',
    'ID',
    'Name',
    'Photo',
    'Flag',
    'Club Logo',
    'Club',
    'Special',
    'Real Face',
    'Release Clause',
    'Joined',
    'Contract Valid Until',
    'Nationality',
    'Loaned From',
    'GKDiving',
    'GKHandling',
    'GKKicking',
    'GKPositioning',
    'GKReflexes',
    'Jersey Number',
    'Value',
    'Wage',
    'International Reputation',
    'Skill Moves',
]

skills_columns = [
    'LS',
    'ST',
    'RS',
    'LW',
    'LF',
    'CF',
    'RF',
    'RW',
    'LAM',
    'CAM',
    'RAM',
    'LM',
    'LCM',
    'CM',
    'RCM',
    'RM',
    'LWB',
    'LDM',
    'CDM',
    'RDM',
    'RWB',
    'LB',
    'LCB',
    'CB',
    'RCB',
    'RB',
]
old_features = [
    'SprintSpeed',
    'Acceleration',
    'Finishing',
    'LongShots',
    'ShotPower',
    'Positioning',
    'Penalties',
    'Volleys',
    'ShortPassing',
    'Vision',
    'Crossing',
    'LongPassing',
    'Curve',
    'FKAccuracy',
    'Marking',
    'StandingTackle',
    'Interceptions',
    'LongPassing',
    'HeadingAccuracy',
    'SlidingTackle',
    'Strength',
    'Stamina',
    'Aggression',
    'Jumping',
    'Dribbling',
    'BallControl',
    'Agility',
    'Balance',
    'Reactions',
]
